name: Dump Test

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: g++ ./test/dump_test.cpp -std=c++17 -o ./a.out
      - name: Run
        run: ./a.out
      - name: Check Output
        run: diff -q ./dump_test_result.txt ./test/dump_test_result.txt
